inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('add_product', views.add_product, name='add_product'),
    path('update_product/<str:pk>/', views.update_product, name='update_product'),
    path('delete_product/<str:pk>/', views.delete_product, name='delete_product')
]

inventory_dj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
]

inventory/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    discount_choice = (('yes', 'yes'), 
                    ('no', 'no'))
    name = models.CharField(max_length=100)
    cost = models.IntegerField()
    stock = models.IntegerField()
    discount = models.CharField(max_length=100, choices=discount_choice)

    def __str__(self):
        return(self.name)

inventory/forms.py
from django.forms import ModelForm
from .models import *

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

inventory/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.

def home(request) :
    products = Product.objects.all()
    return(render(request, 'inventory/home.html', {'products':products}))

def about(request) :
    return(render(request, 'inventory/about.html'))

def add_product(request) :
    if request.method == 'POST' :
        form = ProductForm(request.POST)
        if form.is_valid() :
            form.save()
            return(redirect('/'))
    return(render(request, 'inventory/add_product.html'))

def update_product(request, pk) :
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST' :
        form = ProductForm(request.POST, instance=product)
        if form.is_valid() :
            form.save()
            return(redirect('/'))
    return(render(request, 'inventory/update_product.html',{'form':form}))

def delete_product(request, pk):
    product = Product.objects.get(id=pk)
    if request.method == 'POST' :
        product.delete()
        return(redirect('/'))
    return(render(request, 'inventory/delete_product.html', {'product':product}))

inventory/templates/inventory/about.html
{% extends 'inventory/main.html' %}
{% block content %}
    <h1>About</h1>
{% endblock %}

inventory/templates/inventory/add_product.html
{% extends 'inventory/main.html' %}
{% block content %}
    <!-- <hr>
    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
        <div class="col-2">
            Procuct name:
            <input type="text" class="form-control" placeholder="Name" id='name'>
        </div>
        <div class="col-2">
            Cost:
            <input type="text" class="form-control" placeholder="Cost" id='cost'>
        </div>
        <div class="col-2">
            Stock:
            <input type="text" class="form-control" placeholder="Stock" id='stock'>
        </div>
        <div class="col-2">
            Discount:
            <select class="custom-select mr-sm-2" id="discount">
            <option value="yes">Yes</option>
            <option value="no">No</option>
            </select>
        </div>
        <div class="col-2">
            <button type="submit" class="btn btn-dark">Add/Update Product</button>
        </div>
        </div>
    </form> -->
    <form class="add_update" method="POST">
        {% csrf_token %}
        <div >
            <tr><th><label for="id_name">Name:</label></th>
            <td><input type="text" class="form-control" name="name" maxlength="100" required id="id_name"></td></tr>
        </div>
        <div >
            <tr><th><label for="id_cost">Cost:</label></th>
            <td><input type="number" class="form-control" name="cost" required id="id_cost"></td></tr>
        </div>
        <div >
            <tr><th><label for="id_stock">Stock:</label></th>
            <td><input type="number" class="form-control" name="stock" required id="id_stock"></td></tr>
        </div>
        <div >
            <tr><th><label for="id_discount">Discount:</label></th>
            <td><select class="form-control" name="discount" required id="id_discount">
            <option value="" selected>---------</option>
            <option value="yes">yes</option>
            <option value="no">no</option>
            </select></td></tr>
        </div>
        <div >
            <button type="submit" class="btn btn-dark">Add Product</button>
        </div>
    </form>

    <style>
        .add_update{
            margin: auto;
            margin-top: 80px;
            margin-bottom: 5%;
            width: 70%;
            line-height: 50px;
        }
    </style>
{% endblock %}

inventory/templates/inventory/delete_product.html
{% extends 'inventory/main.html' %}
{% block content %}
    <form class="form" method="POST">
        {% csrf_token %}
        <p> Are you sure you want to DELETE "{{product}}" ?</p>
        <input type="submit" name="Confirm" id='submit' class="btn btn-danger" value="Delete">
        <a href="{% url 'home'%}" class="btn btn-success" role="button" id='add'>Cancle</a>
    </form>
    <style>
        .form{
            margin: auto;
            width: 80%;
            margin-top: 80px;
            font-size: 30px;
        }
        #submit{
            font-size: 16px;
        }
    </style>
{% endblock %}

inventory/templates/inventory/footer.html
<!-- Footer -->
<footer class="footer">

<!-- Copyright -->
    <div class="footer-copyright text-center py-3" id='text'>© 2020 Copyright:
        <a href="{% url 'home' %}"> 192.168.16.160:8000</a>
    </div>
<!-- Copyright -->

</footer>

<style>
    .footer{
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #272424;
    }
    #text{
        color: blanchedalmond;
    }
</style>

inventory/templates/inventory/home.html
{% extends 'inventory/main.html' %}
{% block content %}
    <div class='product'>
        <hr>
        <a href="{% url 'add_product' %}" class="btn btn-info" role="button" id='add'>Add Product</a>
        <hr>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Cost</th>
                <th scope="col">Stock</th>
                <th scope="col">Discount</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for i in products %}
            <tr>
                <th scope="row">{{i.id}}</th>
                <td>{{i.name}}</td>
                <td>{{i.cost}}</td>
                <td>{{i.stock}}</td>
                <td>{{i.discount}}</td>
                <td><a href="{% url 'update_product' i.id%}" class="btn btn-success" role="button" id='add'>Update</a></td>
                <td><a href="{% url 'delete_product' i.id%}" class="btn btn-danger" role="button" id='add'>Delete</a></td>
            </tr>
            {% endfor %}
            <!-- <tr>
                <th scope="row">eg id 1</th>
                <td>eg name</td>
                <td>eg cost</td>
                <td>eg stock</td>
                <td>eg availibility</td>
                <td><a href="#" class="btn btn-success" role="button" id='add'>Update</a></td>
                <td><a href="#" class="btn btn-danger" role="button" id='add'>Delete</a></td>
            </tr> -->
            </tbody>
        </table>
    </div>
    <style>
        .product{
            margin: auto;
            width: 80%;
            margin-top: 80px;
            margin-bottom: 5%;
        }
        #add{
            margin: auto;
            width: 100%;
        }
    </style>
{% endblock %}

inventory/templates/inventory/main.html
<!DOCTYPE html>
<html>
<head>
    <title>Inventory</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
{% include 'inventory/navbar.html' %}
<body>
    {% block content %}
    {% endblock %}
</body>
{% include 'inventory/footer.html' %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

<style>
    #body{
        margin: auto;
        width: 80%;
    }
</style>

inventory/templates/inventory/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='nb'>
  <a class="navbar-brand" href="{% url 'home' %}" id='navbar'>Inventory</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
    </ul>
  </div>
</nav>
<style>
  #nb{
      position: fixed;
      left: 0;
      top: 0;
      width: 100%;
      background-color: #272424;
  }
</style>

inventory/templates/inventory/test.html
<tr><th><label for="id_name">Name:</label></th>
    <td><input type="text" name="name" maxlength="100" required id="id_name"></td></tr>
    
<tr><th><label for="id_cost">Cost:</label></th>
    <td><input type="number" name="cost" required id="id_cost"></td></tr>

<tr><th><label for="id_stock">Stock:</label></th>
    <td><input type="number" name="stock" required id="id_stock"></td></tr>

<tr><th><label for="id_discount">Discount:</label></th>
    <td><select name="discount" required id="id_discount">
  <option value="" selected>---------</option>

  <option value="yes">yes</option>

  <option value="no">no</option>

</select></td></tr>

inventory/templates/inventory/update_product.html
{% extends 'inventory/main.html' %}
{% block content %}
    <form class="form" method="POST">
        {% csrf_token %}
        <div class="update">
            {{form}}
            <input type="submit" name="Update" value="Update" class="btn btn-success" id="btn">
        </div>
    </form>
    <style>
        .form{
            margin-top: 80px;
        }
        .update{
            margin: auto;
            width: 80%;
            line-height: 30px;
        }
        input{
            border-radius: 3px;
            border-width: .5px;
            border-style: solid;
            width: 100%;
            padding-left: 5px;
        }
        label{
            line-height: 40px;
            width: 70%
        }
        #id_discount{
            position: relative;
            left: -70%;
            top: 30px;
        }
        #btn{
            position: relative;
            top: 30px;
        }
    </style>
{% endblock %}